stages:
- pages

pages:
  image: alpine:latest
  stage: pages
  script:
  - mkdir /tmp/public
  - cp -r * /tmp/public/
  - mv /tmp/public public
  artifacts:
    paths:
    - public
  publish: public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

