stages:
- pages

pages:
  image: alpine:latest
  stage: pages
  script:
  - mkdir /tmp/public
  - cp -r * /tmp/public/
  artifacts:
    paths:
    - /tmp/public
  publish: /tmp/public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
