stages:
- pages

pages:
  stage: pages
  script:
  - mkdir public
  - cp -r * public/
  artifacts:
    paths:
    - public
  publish: public
  # rules:
  # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
